#!/usr/bin/env python2

import sys
import subprocess
import telnetlib

GITW_HOST = "192.168.101.196"
GITW_PORT = 9988

# This is a post-update script for git to send a proper string
# to a gitw server. The server will then begin to checkout, build and
# test the newest commit of the project.

gitStdout = ""
cmd = 'git --no-pager log -1 --pretty=format:"%h|%an -- %s"'
try:
    proc = subprocess.Popen(cmd, shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    return_code = proc.wait()
    stderr = proc.stderr.read()
    if len(stderr) > 1:
	sys.stderr.write(stderr)
        exit(-2)
    gitStdout = proc.stdout.read()
except Exception,e:
    sys.stderr.write("Error executing git log: " + str(e) + "\n")
    exit(-4)
else:
    project = "test"
    print "Building gitw project '%s' ... '%s'" % (project,gitStdout)
    try:
        message = str(project + "|" + gitStdout + "\r\n")
        client = telnetlib.Telnet(GITW_HOST, GITW_PORT)
        client.write(message)
        client.close()
    except Exception, e:
        sys.stderr.write("Error communicating with gitw server: " + str(e) + "\n")
        exit(0)
